### ISSUE TITLE
Reaction issue

### ISSUE THREAD

**Issue by gyeyoqu** [Tyler3D/Multi-Ogar-Edited-Unlimited#68]
The big issue why i not download your version o megabyte version is because both is so laggy i tested in my pc and the less laggy is the luka967 version, you can do better perfomance?

**Comment by gyeyoqu** [comment]
Compare the mouse reactiom of gota.io and other multiogar servers

**Comment by Tyler3D** [comment]
Luka's version is slower than Megabyte's version due to the calculations done on splitting. My version is around the same range. You can still play with 750 bots on my version maybe even 1 thousand. I think It's your computer. But, I'm going to keep this open so, I can give you stats when I get home
